// <auto-generated />
using System;
using Demo.DataAccess.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demo.DataAccess.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Demo.DataAccess.Entities.DepartmentModel.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 10L, 10);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("LastModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Departments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 90,
                            Code = "FIN",
                            CreatedBy = 0,
                            CreatedOn = new DateOnly(2021, 9, 23),
                            Description = "Handles company finances, payroll, and budgets",
                            IsDeleted = false,
                            LastModifiedBy = 0,
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 50,
                            Code = "MKT",
                            CreatedBy = 0,
                            CreatedOn = new DateOnly(2022, 9, 23),
                            Description = "Focuses on advertising, branding, and outreach",
                            IsDeleted = false,
                            LastModifiedBy = 0,
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 60,
                            Code = "SLS",
                            CreatedBy = 0,
                            CreatedOn = new DateOnly(2023, 9, 23),
                            Description = "Responsible for sales operations and client relationships",
                            IsDeleted = false,
                            LastModifiedBy = 0,
                            Name = "Sales"
                        },
                        new
                        {
                            Id = 70,
                            Code = "RND",
                            CreatedBy = 0,
                            CreatedOn = new DateOnly(2019, 9, 18),
                            Description = "Innovates and develops new products and services",
                            IsDeleted = false,
                            LastModifiedBy = 0,
                            Name = "R&D"
                        },
                        new
                        {
                            Id = 80,
                            Code = "SUP",
                            CreatedBy = 0,
                            CreatedOn = new DateOnly(2024, 9, 23),
                            Description = "Provides technical and customer support",
                            IsDeleted = false,
                            LastModifiedBy = 0,
                            Name = "Support"
                        });
                });

            modelBuilder.Entity("Demo.DataAccess.Entities.EmployeEntities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("varchar(150)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HiringDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("LastModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1004,
                            Address = "101-Cairo-Maadi-Egypt",
                            Age = 28,
                            CreatedBy = 0,
                            DepartmentId = 10,
                            Email = "alice.johnson@example.com",
                            EmployeeType = "FullTime",
                            Gender = "Female",
                            HiringDate = new DateTime(2023, 9, 23, 16, 49, 19, 492, DateTimeKind.Local).AddTicks(6483),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedBy = 0,
                            Name = "Alice Johnson",
                            PhoneNumber = "01012345678",
                            Salary = 12000m
                        },
                        new
                        {
                            Id = 1005,
                            Address = "202-Giza-Dokki-Egypt",
                            Age = 32,
                            CreatedBy = 0,
                            DepartmentId = 20,
                            Email = "omar.khaled@example.com",
                            EmployeeType = "PartTime",
                            Gender = "Male",
                            HiringDate = new DateTime(2022, 9, 23, 16, 49, 19, 492, DateTimeKind.Local).AddTicks(6516),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedBy = 0,
                            Name = "Omar Khaled",
                            PhoneNumber = "01098765432",
                            Salary = 15000m
                        },
                        new
                        {
                            Id = 1006,
                            Address = "303-Alexandria-SidiBishr-Egypt",
                            Age = 26,
                            CreatedBy = 0,
                            DepartmentId = 40,
                            Email = "mona.adel@example.com",
                            EmployeeType = "Intern",
                            Gender = "Female",
                            HiringDate = new DateTime(2024, 9, 23, 16, 49, 19, 492, DateTimeKind.Local).AddTicks(6522),
                            IsActive = false,
                            IsDeleted = false,
                            LastModifiedBy = 0,
                            Name = "Mona Adel",
                            PhoneNumber = "01122334455",
                            Salary = 10000m
                        },
                        new
                        {
                            Id = 1007,
                            Address = "404-Cairo-NasrCity-Egypt",
                            Age = 40,
                            CreatedBy = 0,
                            DepartmentId = 50,
                            Email = "ahmed.samir@example.com",
                            EmployeeType = "FullTime",
                            Gender = "Male",
                            HiringDate = new DateTime(2015, 9, 23, 16, 49, 19, 492, DateTimeKind.Local).AddTicks(6527),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedBy = 0,
                            Name = "Ahmed Samir",
                            PhoneNumber = "01234567890",
                            Salary = 20000m
                        },
                        new
                        {
                            Id = 1008,
                            Address = "505-Cairo-Heliopolis-Egypt",
                            Age = 24,
                            CreatedBy = 0,
                            DepartmentId = 60,
                            Email = "sara.nabil@example.com",
                            EmployeeType = "Contract",
                            Gender = "Female",
                            HiringDate = new DateTime(2025, 1, 23, 16, 49, 19, 492, DateTimeKind.Local).AddTicks(6533),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedBy = 0,
                            Name = "Sara Nabil",
                            PhoneNumber = "01566778899",
                            Salary = 9000m
                        },
                        new
                        {
                            Id = 1009,
                            Address = "606-Giza-Haram-Egypt",
                            Age = 35,
                            CreatedBy = 0,
                            DepartmentId = 70,
                            Email = "youssef.hany@example.com",
                            EmployeeType = "FullTime",
                            Gender = "Male",
                            HiringDate = new DateTime(2020, 9, 23, 16, 49, 19, 492, DateTimeKind.Local).AddTicks(6541),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedBy = 0,
                            Name = "Youssef Hany",
                            PhoneNumber = "01055667788",
                            Salary = 17000m
                        },
                        new
                        {
                            Id = 1010,
                            Address = "707-Cairo-Zamalek-Egypt",
                            Age = 29,
                            CreatedBy = 0,
                            DepartmentId = 80,
                            Email = "laila.hassan@example.com",
                            EmployeeType = "PartTime",
                            Gender = "Female",
                            HiringDate = new DateTime(2021, 9, 23, 16, 49, 19, 492, DateTimeKind.Local).AddTicks(6583),
                            IsActive = false,
                            IsDeleted = false,
                            LastModifiedBy = 0,
                            Name = "Laila Hassan",
                            PhoneNumber = "01299887766",
                            Salary = 11000m
                        },
                        new
                        {
                            Id = 1011,
                            Address = "808-Cairo-Downtown-Egypt",
                            Age = 45,
                            CreatedBy = 0,
                            DepartmentId = 90,
                            Email = "khaled.mostafa@example.com",
                            EmployeeType = "FullTime",
                            Gender = "Male",
                            HiringDate = new DateTime(2010, 9, 23, 16, 49, 19, 492, DateTimeKind.Local).AddTicks(6589),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedBy = 0,
                            Name = "Khaled Mostafa",
                            PhoneNumber = "01044556677",
                            Salary = 25000m
                        },
                        new
                        {
                            Id = 1012,
                            Address = "909-Alexandria-Montaza-Egypt",
                            Age = 22,
                            CreatedBy = 0,
                            DepartmentId = 10,
                            Email = "nour.ahmed@example.com",
                            EmployeeType = "Intern",
                            Gender = "Female",
                            HiringDate = new DateTime(2025, 3, 23, 16, 49, 19, 492, DateTimeKind.Local).AddTicks(6594),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedBy = 0,
                            Name = "Nour Ahmed",
                            PhoneNumber = "01533445566",
                            Salary = 8000m
                        },
                        new
                        {
                            Id = 1013,
                            Address = "1001-Cairo-Mokattam-Egypt",
                            Age = 38,
                            CreatedBy = 0,
                            DepartmentId = 20,
                            Email = "hussein.ali@example.com",
                            EmployeeType = "Contract",
                            Gender = "Male",
                            HiringDate = new DateTime(2018, 9, 23, 16, 49, 19, 492, DateTimeKind.Local).AddTicks(6600),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedBy = 0,
                            Name = "Hussein Ali",
                            PhoneNumber = "01155667788",
                            Salary = 18000m
                        });
                });

            modelBuilder.Entity("Demo.DataAccess.Entities.IdentityEntities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Demo.DataAccess.Entities.EmployeEntities.Employee", b =>
                {
                    b.HasOne("Demo.DataAccess.Entities.DepartmentModel.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Demo.DataAccess.Entities.IdentityEntities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Demo.DataAccess.Entities.IdentityEntities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Demo.DataAccess.Entities.IdentityEntities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Demo.DataAccess.Entities.IdentityEntities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Demo.DataAccess.Entities.DepartmentModel.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
